// Generated by CoffeeScript 1.8.0

/*
TODO:
  1. Make annon function that creates and event listener on page bound to an "onactive" area
  2. When chat area is active listen for an enter button press
  3. Have function that parses message for special characters or patterns.
 */
var chatActive, sendMessage;

$("#chat_area").click(function() {
  return chatActive;
});

chatActive = function() {
  alert("stuff");
  return document.addEventListener('keydown', sendMessage(event));
};

sendMessage = function(event) {
  return alert(event);
};
